name: OpenImageIO - Artifact

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Environment Variables
      run: |
        OIIO_FAMILY=OpenImageIO
        OIIO_VERSION=Release-2.2.18.0
        OIIO_PACKAGE=$OIIO_FAMILY-$OIIO_VERSION
        echo ::set-env name=OIIO_FAMILY::$OIIO_FAMILY
        echo ::set-env name=OIIO_VERSION::$OIIO_VERSION
        echo ::set-env name=OIIO_PACKAGE::$OIIO_PACKAGE
    - name: Update & Install APT Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get --yes install build-essential cmake libboost-all-dev libilmbase-dev libopenexr-dev libpng-dev libtiff5-dev
    - name: Download Source
      run: |
        wget https://github.com/OpenImageIO/oiio/archive/$OIIO_VERSION.tar.gz -O $OIIO_PACKAGE.tar.gz
        mkdir $OIIO_PACKAGE
        tar -xvf $OIIO_PACKAGE.tar.gz -C $OIIO_PACKAGE --strip-components=1
    - name: Build Package
      run: |
        cd $OIIO_PACKAGE
        make PYTHON_VERSION=3.8
    - uses: actions/upload-artifact@master
      with:
        name: OpenImageIO-Release-2.2.18.0
        path: OpenImageIO-Release-2.2.18.0/dist