name: OpenImageIO - Artifact

on: [push]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Environment Variables
      run: |
         echo "CI_PYTHON_VERSION=3.8" >> $GITHUB_ENV
         echo "CI_OIIO_VERSION=2.2.18.0" >> $GITHUB_ENV
         echo "CI_OIIO_PACKAGE=OpenImageIO-Release-2.2.18.0" >> $GITHUB_ENV
    - name: Update & Install APT Package Dependencies
      run: |
        sudo apt-get update
        sudo apt-get --yes install build-essential cmake libboost-all-dev libilmbase-dev libopenexr-dev libpng-dev libtiff5-dev
    - name: Download Source
      run: |
        wget https://github.com/OpenImageIO/oiio/archive/$CI_OIIO_VERSION.tar.gz -O $CI_OIIO_PACKAGE.tar.gz
        mkdir $CI_OIIO_PACKAGE
        tar -xvf $CI_OIIO_PACKAGE.tar.gz -C $CI_OIIO_PACKAGE --strip-components=1
    - name: Build Package
      run: |
        cd $CI_OIIO_PACKAGE
        make PYTHON_VERSION=$CI_PYTHON_VERSION
    - uses: actions/upload-artifact@master
      with:
        name: OpenImageIO-Release-2.2.18.0
        path: OpenImageIO-Release-2.2.18.0/dist